name: APPROVE
on: pull_request

permissions:
  pull-requests: write
jobs:
  approve:
    runs-on: ubuntu-latest
    
    steps:
      - run: |
          curl --request POST \
          --url https://api.github.com/repos/${{github.repository}}/pulls/${{github.event.pull_request.number}}/reviews
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{secrets.GITHUB_TOKEN}}"\
          -H "X-GitHub-Api-Version: 2022-11-28" \
          -d '{"commit_id":${{github.sha}},"body":"This is close to perfect!","event":"Approve"}'
      
      
